In [8]:
import numpy as np

In [9]:
np_array = np.array(
    [
        [1, 2, 3, 4], 
        [5, 6, 7, 8],
    ]
)

In [10]:
print(np_array)
print(np_array.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)


In [15]:
np_array = np.ones((10, 10), dtype = float)
print(np_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [16]:
reshaped_np_array = np_array.reshape((2, 50))
print(reshaped_np_array)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
  1. 1.]]


In [18]:
import sys
python_list = range(1000)
print(f"Python list size: {sys.getsizeof(python_list) * len(python_list)}")

np_array = np.arange(1000)
print(f"Numpy Array size:{np_array.size * np_array.itemsize}")

Python list size: 48000
Numpy Array size:8000


In [22]:
import time
array_size = 1_000_00
python_list1 = range(array_size)
python_list2 = range(array_size)

start_time = time.time()
python_multiplication = [(n1 * n2) for n1, n2 in zip(python_list1, python_list2)]
print(f"Python multiplication time used:{time.time() - start_time}")

np_array1 = np.arange(array_size)
np_array2 = np.arange(array_size)
start_time = time.time()
numpy_multiplication = np_array1 * np_array2
print(f"Numpy nultiplication time used:{time.time() - start_time}")


Python multiplication time used:0.006583452224731445
Numpy nultiplication time used:0.00040268898010253906


In [24]:
np_array = np.arange(1, 21).reshape((4, 5))
print(np_array)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]


In [25]:
print(np.argmin(np_array))
print(np.argmax(np_array))
print(np.mean(np_array))
print(np.median(np_array))

0
19
10.5
10.5


In [29]:
from numpy import savetxt
np_array = np.array([1, 2, 3, 4, 5])
print(np_array)
savetxt("data.csv", np_array, delimiter=",")

[1 2 3 4 5]


In [30]:
from numpy import loadtxt

data = loadtxt("data.csv", delimiter=",")
print(data.astype(int))

[1 2 3 4 5]
