In [3]:
import numpy as np

In [4]:
np_array = np.array([1, 2, 3])
print(type(np_array))
print(np_array.shape)

<class 'numpy.ndarray'>
(3,)


In [11]:
zero_array = np.zeros((7, 7))
print(zero_array)

one_array = np.ones((7, 7))
print(one_array)

full_array = np.full((7, 7), 7)
print(full_array)

empty_array = np.empty((7, 7))
print(empty_array)


[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]
[[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
[[3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]
 [3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323 3.5e-323]]
